---
- name: 'gather os specific variables'
  include_vars: "{{ vars_file }}"
  loop:
    - 'default.yml'
    - "{{ ansible_facts['os_family'] | lower }}.yml"
    - "{{ ansible_facts['distribution'] | lower }}.yml"
    - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] }}.yml"
  loop_control:
    loop_var: vars_file
  when: "(vars_file is abs and vars_file is file) or (vars_file is not abs and (role_path ~ '/vars/' ~ vars_file) is file)"

- name: 'install iptables'
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ iptables_packages }}"

- name: 'install iptables setup script'
  template:
    src: 'firewall.sh.j2'
    dest: '/usr/local/sbin/firewall.sh'
    owner: root
    group: root
    mode: 0755
  register: _iptables_script

- name: 'activate and persist rules'
  command: "{{ item }}"
  async: 12
  poll: 1
  when: "_iptables_script is changed"
  loop:
    - '/usr/local/sbin/firewall.sh restart'
    - '/usr/local/sbin/firewall.sh save'

- name: 'enable and start'
  service:
    name: "{{ item }}"
    enabled: true
    state: "{{ ansible_facts['is_chroot'] | ternary(omit, 'started') }}"
  loop: "{{ iptables_services }}"
